title: "International Berlin Community (IBC)"
email: "contact@ibc.org"
description: "Promoting international understanding, tolerance, cultural exchange, and building an inclusive community in Berlin through social events."
baseurl: ""
url: "https://your-username.github.io/your-ngosite"
twitter_username: "your-username"
github_username: "your-username"

theme: minima

plugins:
  - jekyll-feed
